### ISSUE TITLE
Initial Meeting Notes

### ISSUE THREAD

**Issue by mimorel** [Audio-Project-Workgroup/Vocal_Analysis#1]
### Goal: 
Create a application that allows users to track their pitch correctness. Users will upload the midi file that they are attempting to mimic and an audio file of their voice. The application will analyze how well the user's pitch matched the given file, and show the user any areas that they did not get right. The application will then provide the user with a corrected version of their vocal recording, with the corrected pitches. 
The application may have a small library of starter files that we provide to test the application.

This would be a application using the Juce framework, that could later may be turned into a plugin. 
#### 1. Pitch Detection
Use SFT to detect the pitches of the singer and the target vocal track.
#### 2. Autotune
Use simple pitch change (speeding up /slowing down) to autotune any pitches in the users recording that are incorrect. 
#### 3. Voice timbre (stretch)
Analyze characteristics, such as breathiness and warmth, in the users voice. We were thinking we could use some machine learning to change the characteristics of a users voice. Resources in the discord channel. 
#### 4. Multiple input sources for given file/ (stretch) 
Instead of only accepting midi files as the target audio, we mentioned having other types of audio files, perhaps including 
isolating voice from audio files.
#### 6. Allow users to export audio files (stretch)
Could be used for going from voice to instrument (via midi file)

**Comment by simonlind90** [comment]
Moved this to Discussion since issues is more used for development tasks: 
https://github.com/Audio-Project-Workgroup/Vocal_Analysis/discussions/2
